paths:
  /auth/register:
    post:
      summary: Register To System
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                role: 
                  type: string
      responses:
        "201":
          summary: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Data"
        "409":
          description: Conflict

  /auth/login:
    post:
      summary: Login To System
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        "201":
          summary: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Data"
        "401":
          description: Unauthorize

  /product:
    post:
      summary: Create new Product
      tags:
        - product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: string
                shortDescription:
                  type: string
                SKU:
                  type: string
                quantity:
                  type: number
      responses:
        "201":
          summary: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Data"
        "401":
          description: Unauthorize

    get:
      summary: Get All Products
      tags:
        - product
      requestBody:
        required: false
        content:
          application/json:
      responses:
        "201":
          summary: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Data"
        "401":
          description: Unauthorize

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        password:
          type: string
        address:
          type: string
        phone:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [user, admin]
        avatar:
          type: string

    Product:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        price:
          type: string
        description:
          type: string
        shortDescription:
          type: string
        SKU:
          type: string
        rating:
          type: string
        quantity:
          type: number
        image:
          type: [string]

    Data:
      type: object
      properties:
        success:
          type: boolean
        statusCode:
          type: number
        data:
          type: object
        message:
          type: string
        pagination:
          tye: string
